# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180620_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pics',
            field=models.ImageField(default=b'meberpage/media/background.jpg', upload_to=b''),
        ),
    ]
