# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180622_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pics',
            field=models.ImageField(default=b'media/blank.png', upload_to=b''),
        ),
    ]
